### PR TITLE
Update ClusterPolicy to be compatible with Kyverno >= 1.4.0

### PR DESCRIPTION
**Pull request by stefanprodan**
Ref: https://github.com/fluxcd/flux2-multi-tenancy/pull/37#issuecomment-896131898

### CODE REVIEW

**Comment by kacejot** [comment]
Hi @stefanprodan, I tried to reproduce the issue with `kyverno-1.4-fix` branch with both merged `main` and not merged one.
I could not reproduce the issue. Here is my fork with `kyverno-1.4-fix` merged into `main`: https://github.com/kacejot/flux2-multi-tenancy

Here is how I installed flux:
```bash
#!/bin/sh

set -eu

flux install --log-level debug
flux create source git flux-system --url=https://github.com/kacejot/flux2-multi-tenancy --branch main
flux create kustomization flux-system --source=flux-system --path=./clusters/staging
```

And here is my test run:
```bash
#!/bin/bash

set -eux

kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
kubectl -n flux-system wait kustomization/kyverno-policies --for=condition=ready --timeout=1m
kubectl -n flux-system wait kustomization/tenants --for=condition=ready --timeout=1m
```

Here is the result for both runs (merged main and not merged):
```bash
maxim@MS-7A70 ~/Workspace/flux2-multi-tenancy                                                 [19:03:26] 
> $ ./run.sh                                                                                   [±main ●]
+ kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
kustomization.kustomize.toolkit.fluxcd.io/kyverno condition met
+ kubectl -n flux-system wait kustomization/kyverno-policies --for=condition=ready --timeout=1m
kustomization.kustomize.toolkit.fluxcd.io/kyverno-policies condition met
+ kubectl -n flux-system wait kustomization/tenants --for=condition=ready --timeout=1m
kustomization.kustomize.toolkit.fluxcd.io/tenants condition met

```

**Comment by kacejot** [comment]
@stefanprodan, could you please help me to reproduce this?

**Comment by stefanprodan** [comment]
To make Flux use this branch you need to set:
```
flux create source git flux-system --url=https://github.com/kacejot/flux2-multi-tenancy --branch kyverno-1.4-fix
```

**Comment by kacejot** [comment]
Hi @stefanprodan,

I also tried to run with `kyverno-1.4-fix` branch and got the same result:
```bash
#!/bin/bash
set -eux

flux install --log-level debug
flux create source git flux-system --url=https://github.com/fluxcd/flux2-multi-tenancy --branch=kyverno-1.4-fix
flux create kustomization flux-system --source=flux-system --path=./clusters/staging
```

Here is my test run:
```bash
#!/bin/bash

set -eux

kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
kubectl -n flux-system wait kustomization/kyverno-policies --for=condition=ready --timeout=1m
kubectl -n flux-system wait kustomization/tenants --for=condition=ready --timeout=1m
```
And the result:
```
umka@polarbear ~/bin                                                                                                             [18:27:00] 
> $ ./run.sh                                                                                                                               
+ kubectl -n flux-system wait kustomization/kyverno --for=condition=ready --timeout=1m
kustomization.kustomize.toolkit.fluxcd.io/kyverno condition met
+ kubectl -n flux-system wait kustomization/kyverno-policies --for=condition=ready --timeout=1m
kustomization.kustomize.toolkit.fluxcd.io/kyverno-policies condition met
+ kubectl -n flux-system wait kustomization/tenants --for=condition=ready --timeout=1m
kustomization.kustomize.toolkit.fluxcd.io/tenants condition met
                                                                          
```

**Pull request merged**
